flags:
  xmonad-extras:
    with_hint: false
    with_mpd: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- X11-xft-0.3.1
- libmpd-0.9.0.4
- xmonad-contrib-0.12
- xmonad-extras-0.12.1
resolver: lts-6.5
